### ISSUE TITLE
Tracking & admin interface over service (re)runs

### ISSUE THREAD

**Issue by kohlhase** [dginev/CorTeX#13]
with the nice "look into the run status" interface, it would be very good if we had some kind of a log of the reruns, so that we can always see what is going on. The rerun button in the lower cornder should generate a generic log entry like "rerun errors missing macro \includegraphics" or "rerun warnings". It would also be good if the user can add some comment to that. 
In the user interface we could have an entry "currently running" and then list all the current ``run tasks''.

**Comment by dginev** [comment]
The reporting interface you request is a significant amount of work, that I could invest in shipping the final corpus, so I may postpone it until after the 2015 dataset is ready.

**Comment by kohlhase** [comment]
I am aware that there are priorization issues, but I thought I would just note the idea. BTW, this might be something a student could do?

**Comment by dginev** [comment]
Most definitely a student can do it yes. If volunteers start to appear, they can be pointed here freely.

**Comment by dginev** [comment]
This issue should be unified with the older:
> CorTeX should keep a log of who did what in the system and display it as a timeline (of actions).

https://github.com/dginev/deprecated-CorTeX/issues/32

which is still a good admin addition

**Comment by dginev** [comment]
Finally at a point to attack this, as the infrastructure is in place, and we now have multiple services that may require tracking reports, now that [engrafo is using cortex](https://github.com/arxiv-vanity/engrafo/issues/592) as a development harness.

Should have a PR ready this week, already have a DB model in mind, and Michael's interface suggestions haven't aged a day, they're exactly what I plan to implement.

**Comment by dginev** [comment]
Done, populating with arxiv historical runs, and will send around an announcement email to the arXMLiv list.
