### ISSUE TITLE
Transparent DevOps History and Background Queue

### ISSUE THREAD

**Issue by kohlhase** [dginev/CorTeX#14]
Original request: Maintain a history of return values like http://arxmliv.kwarc.info/history.php that would make cortex much more demoable.

**Comment by dginev** [comment]
I am not sure if the effort to fully automate this would be worthwhile, given how rarely a full rerun happens. I can instead see maintaining a small JSON file on the mercury server which is updated by hand every 3-4 months or so, which is then used as a source for visualization.

That file can be hosted in an official arXMLiv repository, or if we decide not to have one - as an auxiliary file in the cortex repository. Does that sound reasonable?

**Comment by kohlhase** [comment]
absolutely reasonable. I just did not want the data to be lost. You should probably seed the json file from your past heads-up mails.

**Comment by dginev** [comment]
Have been thinking a little about the implications of certain operations being too slow at scale to finish in a reasonable time for a web request (e.g. 20 seconds). For example, marking the entire arXiv corpus for rerun can realistically take minutes, if not tens of minutes to execute.

I am at present finishing a disciplined backend refactor that provides a lot of tightness and clarity to the DB interfacing logic, and makes upgrades in the "cortex web interface operations" direction easier.

I envision the following for a first upgrade pass:
 * Introduce `web_ops_queue` and `web_ops_history`  tables that record all requests that modify the cortex state.  They should have timestamps, as well as an "owner" that executed them.

 * On "rerun completions" connect historical results from the main "service report" view, such as http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html to the respective completed operation in `web_ops_history`. 

 * Expose the 1) current queue, 2) job history and 3) result history in the web interface for inspection.

This is very similar to the [resque](https://github.com/resque/resque) interface, and i am even half-tempted to think about integrating resque directly here, but it may be simpler/faster to add these 3 items on their own.

**Comment by dginev** [comment]
Ah this is a duplicate to #13 , which I think achieves both a tracking purpose and a history purpose, since the reports are live and auto-track new service (re-)runs.

Can close!
