### ISSUE TITLE
percentages relative to converted jobs

### ISSUE THREAD

**Issue by kohlhase** [dginev/CorTeX#15]
The current percentages in the top-level page are all relative to the full number of jobs. During re-runs that makes it difficult to judge how things are going. It would be good to have another row of percentages relative to the already-converted jobs. That should be much more stable against re-runs.

**Comment by dginev** [comment]
We should discuss this with @brucemiller who also has very concrete ideas of the report percentage numbers.

As it stands it's dangerous to look at the relative numbers, as the rerun goes through uneven windows of jobs - in the beginning the distribution was weighed a lot more heavily towards no problems (I assume it was running the 90s papers), and it is now balancing out roughly 100,000 jobs in. Bruce was saying how the only way he keeps his sanity is if he has percentages that reference the fixed number of all tasks in the corpus.

**Comment by kohlhase** [comment]
I agree that this is a problematic thing that should be discussed. But I just wanted to put the issue where it was not forgotten.

**Comment by brucemiller** [comment]
Overall, with the latest patch, I like the setup and the numbers are nicely assessable. I do see Michaels point, though, and also have a little difficulty there.  Maybe the "total tasks" that are considered over all the clickable sections & sub-pages should be the total tasks that have been processed (whether successful or not), rather than the total in the corpus?  Then the percentages would shift, but not grow, and thus would be easier to see the trends.  As the run completes, the numbers would converge to the same thing we get now (except for tasks that have been outlawed? eg non-latex, "blocked" or whatever). You'd want to use the same sense of total in the Error, Fatal, etc pages as well. 

Other than replacing the "total" in all the scripts for the subpages, the only big catch is in how to display the blue section on the main page. The current percentages wouldn't make sense, but it would still be valuable to see how much processing is to be done an so forth. Maybe a new column?  Or maybe consider the No Problems, Warnings... as subheadings under a new Completed Tasks heading on the same level as Pending,  In Progress.... ?

BTW: CorTeX is flying along now, w/ all of Hulk on the job!

**Comment by kohlhase** [comment]
> Maybe the "total tasks" that are considered over all the clickable sections & sub-pages should be the total tasks that have been processed (whether successful or not), rather than the total in the corpus?

that is exactly what I had in mind.

**Comment by kohlhase** [comment]
> the only big catch is in how to display the blue section on the main page.

I only wanted to add the "relative numbers" to the non-blue part of the page.

**Comment by kohlhase** [comment]
I had not thought of the subpages, but I guess they should work just as the main page.

**Comment by dginev** [comment]
I have the vague memeory that is exactly how the percentages used to be and that they got flipped around to the absolutes.

As someone who is not only interested in latexml's performance, but also in the overall progress of a conversion run, the current percentages which are based against the overall corpus numbers are very helpful to me, as I can meaningfully track progress through the categories, and the subpages.

Given that the entire conversion run with HULK takes 4-5 days, it should be a lot less important how the intermediate states are looking, as we see the final numbers soon enough.

**Comment by brucemiller** [comment]
Yeah, overall progress is important too; that was the "catch" part I mentioned. But until Michael convinces you, I'll just watch for 80% pending so I can easily estimate the final numbers :>

**Comment by dginev** [comment]
If we are talking about a small column-extension to only the top progress view,  shown only during conversion runs, I may agree - it would be simple and easy. And can even be done in javascript, since all the data is already served on the page.

**Comment by kohlhase** [comment]
That was indeed what I was thinking of and that would be quite useful. For the sub-pages, the relative sizes are more important (I think) than the absolute ones.

**Comment by dginev** [comment]
Again, Bruce made me change them to the absolute ones for the subpages. I don't think I have the patience to change them back again soon, maybe at a later date :)

**Comment by kohlhase** [comment]
you misunderstand me, I want the subpages to stay as they are, and when i am looking at them I am looking for the relative sizes between the absolute ones. So no change necessary.

**Comment by dginev** [comment]
Ok, so we agree to:
- Keep the subpages as-is
- Add a rerun-only add-on to the main report that shows the percentages scaled as if the "done" jobs were 100% 
- That add-on is of course not needed when the rerun is over, so it will be hidden when no pending tasks are left

The main report in question are pages such as:
http://cortex.mathweb.org/corpus/arXMLiv/tex_to_html

**Comment by kohlhase** [comment]
yes, that sounds great.

**Comment by brucemiller** [comment]
This may be just terminology, but there are several kinds of absolute & "relative" that can trip us up:
- the total number of tasks/documents in the corpos
- the total number of tasks/documents that have currently been processed
- the total number of tasks/documents that fall into a category or are affected by a message in a given category (Fatal; Fatal:expected; Fatal:expected:id).
  And any 2 of those gives us a percentage!

When I was asking for percentages relative to the "absolute" numbers, I was content with the 1st of the above in the denominator.  But after Michael's point, I'd slightly prefer the 2nd.

However, what you've proposed is fine with me.

**Comment by dginev** [comment]
Given the differences are "cosmetic", i.e. all the necessary raw data is already presented in the views, my inner instincts are telling me to give this issue low priority, to "no priority" as there are actual functional improvements missing in other places (and notably there is LLaMaPUn work to do after CorTeX stabilizes). 

Feel free to discuss further, but given how many times I've retouched the percentages (there is always something non-intuitive the moment they are redone :-) ), I'll give them a rest for now, after I implement the minor JavaScript add-on I mentioned above.

**Comment by brucemiller** [comment]
Isn't it gratifying to have "Users"!

**Comment by dginev** [comment]
Hello @brucemiller  and @kohlhase -- you may not remember this issue from 2.5 years ago, but I am cleaning up today so I went and added the jquery-generated "rerun progress" report we discussed here.

Take a look at the current (active) arXiv rerun for a demonstration:

https://corpora.mathweb.org/corpus/arxmliv/tex_to_html

Feedback welcome in the case you would like some extra adjustments.
